<?php
/**
 * Archive Film Club - Installation Script
 *
 * This script helps cPanel users set up the MySQL database
 * Run this script once after uploading files to your server
 *
 * Access: https://yourdomain.com/install.php
 */

// Security: Check if already installed
$envFile = __DIR__ . '/.env';
$lockFile = __DIR__ . '/.installed';

/**
 * Defensive install guard.
 *
 * Primary check: the `.installed` lock file. Secondary check: even if the
 * lock file has been deleted (accidentally via cPanel file manager, or
 * maliciously), we refuse to re-run the installer when an admin user
 * already exists in the database. This prevents credential-reset attacks
 * that rely on removing the lock file.
 */
$alreadyInstalled = file_exists($lockFile);
if (!$alreadyInstalled && file_exists($envFile)) {
    try {
        require_once __DIR__ . '/bootstrap.php';
        if (class_exists('Database')) {
            $db = Database::getInstance();
            $adminCount = (int)$db->fetchColumn(
                "SELECT COUNT(*) FROM users WHERE role IN ('admin','editor') AND is_guest = 0"
            );
            if ($adminCount > 0) {
                $alreadyInstalled = true;
            }
        }
    } catch (Throwable $e) {
        // DB not reachable yet -- normal on first run. Fall through.
    }
}

if ($alreadyInstalled) {
    die('
    <html>
    <head><title>Already Installed</title></head>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px;">
        <h1>Already Installed</h1>
        <p>Archive Film Club is already installed.</p>
        <p><strong>You should delete <code>install.php</code> now</strong> (or uncomment the install.php deny block in <code>.htaccess</code>). If you really need to reinstall from scratch, drop the database tables and remove the <code>.installed</code> file.</p>
        <p><a href="index.php">Go to Site</a> | <a href="admin.php">Go to Admin</a></p>
    </body>
    </html>
    ');
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Process form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    if ($step === 1) {
        // Step 1: Save database configuration
        $config = [
            'DB_HOST' => trim($_POST['db_host'] ?? 'localhost'),
            'DB_PORT' => trim($_POST['db_port'] ?? '3306'),
            'DB_DATABASE' => trim($_POST['db_name'] ?? ''),
            'DB_USERNAME' => trim($_POST['db_user'] ?? ''),
            'DB_PASSWORD' => $_POST['db_pass'] ?? '',
        ];

        // Validate
        if (empty($config['DB_DATABASE']) || empty($config['DB_USERNAME'])) {
            $error = 'Database name and username are required.';
        } else {
            // Test connection
            try {
                $dsn = "mysql:host={$config['DB_HOST']};port={$config['DB_PORT']};charset=utf8mb4";
                $pdo = new PDO($dsn, $config['DB_USERNAME'], $config['DB_PASSWORD'], [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                ]);

                // Check if database exists, create if not
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$config['DB_DATABASE']}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$config['DB_DATABASE']}`");

                // Connection successful - save .env file
                $envContent = "# Archive Film Club - Database Configuration\n";
                $envContent .= "# Generated by install.php on " . date('Y-m-d H:i:s') . "\n\n";
                foreach ($config as $key => $value) {
                    $envContent .= "$key=$value\n";
                }
                $envContent .= "\n# Cache settings\n";
                $envContent .= "CACHE_SEARCH_TTL=1800\n";
                $envContent .= "CACHE_METADATA_TTL=86400\n";
                $envContent .= "CACHE_THUMBNAIL_TTL=604800\n";
                $envContent .= "\n# Feature flags\n";
                $envContent .= "ENABLE_THUMBNAIL_CACHING=true\n";
                $envContent .= "ENABLE_SEARCH_CACHING=true\n";
                $envContent .= "ENABLE_USER_SESSIONS=true\n";
                $envContent .= "ENABLE_API_LOGGING=true\n";

                if (file_put_contents($envFile, $envContent)) {
                    // Restrict permissions so other users on the shared host
                    // cannot read database credentials via the filesystem.
                    // chmod may be a no-op on some cPanel configurations;
                    // suppress errors and continue.
                    @chmod($envFile, 0600);

                    header('Location: install.php?step=2');
                    exit;
                } else {
                    $error = 'Could not write .env file. Please check file permissions.';
                }

            } catch (PDOException $e) {
                $error = 'Database connection failed: ' . $e->getMessage();
            }
        }
    }

    elseif ($step === 2) {
        // Step 2: Run ALL database migrations (001 → latest)
        try {
            require_once __DIR__ . '/db/Database.php';
            $db = Database::getInstance();

            $migrationsDir = __DIR__ . '/db/migrations';
            $migrationFiles = glob($migrationsDir . '/*.sql');
            if (!$migrationFiles) {
                throw new Exception('No migration files found');
            }
            sort($migrationFiles); // 001_*, 002_*, 003_*, 004_*

            foreach ($migrationFiles as $migrationFile) {
                $sql = file_get_contents($migrationFile);

                // Strip SQL line comments BEFORE splitting on `;`. A comment
                // like `-- items; deleting a collection deletes its items.`
                // contains a semicolon in the text, and a naive
                // explode(';', $sql) would split the file mid-comment,
                // yielding a second chunk whose first line is no longer
                // comment-prefixed. MariaDB then tries to parse the comment
                // prose as SQL and errors out with a 1064 syntax error.
                //
                // Our migrations don't use /* ... */ block comments and
                // don't embed `--` inside string literals, so a line-level
                // strip is sufficient and safe. (Extend this if we start
                // using either.)
                $sql = preg_replace('/^\s*--[^\n]*$/m', '', $sql);

                // Split into individual statements
                $statements = array_filter(
                    array_map('trim', explode(';', $sql)),
                    function($s) { return !empty($s); }
                );

                foreach ($statements as $statement) {
                    if (empty(trim($statement))) continue;
                    try {
                        $db->query($statement);
                    } catch (Throwable $e) {
                        // Swallow "already exists / duplicate column" errors
                        // so re-runs and partially-applied migrations don't
                        // block the installer.
                        $msg = $e->getMessage();
                        if (stripos($msg, 'already exists') === false
                            && stripos($msg, 'Duplicate column') === false
                            && stripos($msg, 'Duplicate key name') === false
                            && stripos($msg, 'Multiple primary key') === false) {
                            throw $e;
                        }
                    }
                }
            }

            header('Location: install.php?step=3');
            exit;

        } catch (Exception $e) {
            $error = 'Migration failed: ' . $e->getMessage();
        }
    }

    elseif ($step === 3) {
        // Step 3: Create admin user in the unified `users` table
        // (migration 003). This matches what UserAuthService::login() reads
        // from, so the same credentials work for both admin.php and the
        // front-end login flow.
        $username = trim($_POST['admin_user'] ?? '');
        $password = $_POST['admin_pass'] ?? '';
        $passwordConfirm = $_POST['admin_pass_confirm'] ?? '';
        $email = trim($_POST['admin_email'] ?? '');

        if (empty($username) || empty($password)) {
            $error = 'Username and password are required.';
        } elseif ($password !== $passwordConfirm) {
            $error = 'Passwords do not match.';
        } elseif (strlen($password) < 8) {
            $error = 'Password must be at least 8 characters.';
        } else {
            try {
                require_once __DIR__ . '/db/Database.php';
                $db = Database::getInstance();

                // Reject if an admin account already exists in either table.
                $existingUnified = $db->fetchColumn(
                    "SELECT COUNT(*) FROM users WHERE role IN ('admin','editor') AND is_guest = 0"
                );
                $existingLegacy = 0;
                try {
                    $existingLegacy = $db->fetchColumn("SELECT COUNT(*) FROM admin_users");
                } catch (Throwable $e) { /* table may have been dropped */ }

                if ((int)$existingUnified > 0 || (int)$existingLegacy > 0) {
                    $error = 'An admin user already exists.';
                } else {
                    // Uniqueness guard on username inside `users`.
                    $collision = $db->fetchOne(
                        "SELECT id FROM users WHERE username = ?",
                        [$username]
                    );
                    if ($collision) {
                        $error = 'That username is already taken.';
                    } else {
                        $hash = password_hash($password, PASSWORD_DEFAULT);
                        $db->insert('users', [
                            'username'      => $username,
                            'email'         => $email !== '' ? $email : null,
                            'password_hash' => $hash,
                            'display_name'  => $username,
                            'role'          => 'admin',
                            'is_guest'      => 0,
                            'session_id'    => null,
                            'preferences'   => '{}',
                        ]);

                        header('Location: install.php?step=4');
                        exit;
                    }
                }
            } catch (Exception $e) {
                $error = 'Error creating admin: ' . $e->getMessage();
            }
        }
    }

    elseif ($step === 4) {
        // Step 4: Migrate existing JSON data
        try {
            require_once __DIR__ . '/services/SettingsService.php';
            $settingsService = new SettingsService();

            // Migrate site settings
            $settingsFile = __DIR__ . '/site-settings.json';
            if (file_exists($settingsFile)) {
                $content = file_get_contents($settingsFile);
                $data = json_decode($content, true);
                if ($data) {
                    $settingsService->updateSettings($data);
                }
            }

            // Migrate recommendations
            $recommendationsFile = __DIR__ . '/recommendations.json';
            if (file_exists($recommendationsFile)) {
                $content = file_get_contents($recommendationsFile);
                $data = json_decode($content, true);
                if ($data) {
                    $settingsService->updateRecommendations($data);
                }
            }

            // Migrate featured sections
            $sectionsFile = __DIR__ . '/featured-sections.json';
            if (file_exists($sectionsFile)) {
                $content = file_get_contents($sectionsFile);
                $data = json_decode($content, true);
                if ($data) {
                    $settingsService->updateFeaturedSections($data);
                }
            }

            // Create lock file
            file_put_contents($lockFile, date('Y-m-d H:i:s'));

            header('Location: install.php?step=5');
            exit;

        } catch (Exception $e) {
            $error = 'Migration failed: ' . $e->getMessage();
        }
    }
}

// HTML Output
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install Archive Film Club</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #1a1a2e;
            color: #eee;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: #16213e;
            border-radius: 12px;
            padding: 30px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.3);
        }
        h1 {
            color: #ff0000;
            margin-top: 0;
            font-size: 24px;
        }
        h2 {
            font-size: 18px;
            margin-top: 0;
        }
        .steps {
            display: flex;
            margin-bottom: 30px;
            gap: 5px;
        }
        .step-indicator {
            flex: 1;
            padding: 10px;
            background: #0f3460;
            text-align: center;
            font-size: 12px;
            border-radius: 6px;
        }
        .step-indicator.active {
            background: #ff0000;
            color: white;
        }
        .step-indicator.completed {
            background: #27ae60;
            color: white;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 500;
        }
        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: 100%;
            padding: 12px;
            border: 1px solid #333;
            border-radius: 6px;
            background: #0f3460;
            color: #fff;
            font-size: 14px;
        }
        input:focus {
            outline: none;
            border-color: #ff0000;
        }
        button {
            background: #ff0000;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 16px;
            font-weight: 500;
        }
        button:hover {
            background: #cc0000;
        }
        .error {
            background: #c0392b;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .success {
            background: #27ae60;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .info {
            background: #2980b9;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            font-size: 14px;
        }
        code {
            background: #0f3460;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: monospace;
        }
        a {
            color: #ff0000;
        }
        .btn-secondary {
            background: #0f3460;
            margin-left: 10px;
        }
        .btn-secondary:hover {
            background: #1a4b8c;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Archive Film Club Installation</h1>

        <!-- Progress Steps -->
        <div class="steps">
            <div class="step-indicator <?= $step >= 1 ? ($step > 1 ? 'completed' : 'active') : '' ?>">1. Database</div>
            <div class="step-indicator <?= $step >= 2 ? ($step > 2 ? 'completed' : 'active') : '' ?>">2. Tables</div>
            <div class="step-indicator <?= $step >= 3 ? ($step > 3 ? 'completed' : 'active') : '' ?>">3. Admin</div>
            <div class="step-indicator <?= $step >= 4 ? ($step > 4 ? 'completed' : 'active') : '' ?>">4. Migrate</div>
            <div class="step-indicator <?= $step >= 5 ? 'active' : '' ?>">5. Done!</div>
        </div>

        <?php if ($error): ?>
        <div class="error"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
        <!-- Step 1: Database Configuration -->
        <h2>Step 1: Database Configuration</h2>
        <div class="info">
            <strong>cPanel Users:</strong> Go to cPanel &rarr; MySQL Databases to create a database and user.
            Make sure to add the user to the database with ALL PRIVILEGES.
        </div>

        <form method="POST">
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" name="db_host" value="localhost" required>
            </div>
            <div class="form-group">
                <label>Database Port</label>
                <input type="text" name="db_port" value="3306" required>
            </div>
            <div class="form-group">
                <label>Database Name</label>
                <input type="text" name="db_name" placeholder="e.g., username_filmclub" required>
            </div>
            <div class="form-group">
                <label>Database Username</label>
                <input type="text" name="db_user" placeholder="e.g., username_filmuser" required>
            </div>
            <div class="form-group">
                <label>Database Password</label>
                <input type="password" name="db_pass" required>
            </div>
            <button type="submit">Test Connection &amp; Continue</button>
        </form>

        <?php elseif ($step === 2): ?>
        <!-- Step 2: Run Migrations -->
        <h2>Step 2: Create Database Tables</h2>
        <p>Click the button below to create all required database tables.</p>

        <form method="POST">
            <button type="submit">Create Tables</button>
        </form>

        <?php elseif ($step === 3): ?>
        <!-- Step 3: Create Admin User -->
        <h2>Step 3: Create Admin Account</h2>
        <p>Create your administrator account to manage the site.</p>

        <form method="POST">
            <div class="form-group">
                <label>Admin Username</label>
                <input type="text" name="admin_user" required autocomplete="username">
            </div>
            <div class="form-group">
                <label>Admin Email (optional)</label>
                <input type="email" name="admin_email" autocomplete="email">
            </div>
            <div class="form-group">
                <label>Password (min 8 characters)</label>
                <input type="password" name="admin_pass" required minlength="8" autocomplete="new-password">
            </div>
            <div class="form-group">
                <label>Confirm Password</label>
                <input type="password" name="admin_pass_confirm" required autocomplete="new-password">
            </div>
            <button type="submit">Create Admin Account</button>
        </form>

        <?php elseif ($step === 4): ?>
        <!-- Step 4: Migrate Data -->
        <h2>Step 4: Migrate Existing Data</h2>
        <p>Click below to migrate your existing JSON data (settings, recommendations, sections) to the database.</p>

        <div class="info">
            This will import data from:
            <ul style="margin: 10px 0;">
                <li><code>site-settings.json</code></li>
                <li><code>recommendations.json</code></li>
                <li><code>featured-sections.json</code></li>
            </ul>
            Your original JSON files will not be deleted.
        </div>

        <form method="POST">
            <button type="submit">Migrate Data</button>
            <a href="install.php?step=5" class="btn-secondary" style="display:inline-block; padding:12px 24px; background:#0f3460; color:white; text-decoration:none; border-radius:6px; margin-left:10px;">Skip</a>
        </form>

        <?php elseif ($step === 5): ?>
        <!-- Step 5: Complete -->
        <h2>Installation Complete!</h2>
        <div class="success">
            Archive Film Club has been successfully installed and configured.
        </div>

        <p><strong>Next steps:</strong></p>
        <ul>
            <li>Visit the <a href="admin.php">Admin Panel</a> to manage your site</li>
            <li>Delete or rename <code>install.php</code> for security</li>
            <li>Your JSON files are still present as backups</li>
        </ul>

        <p style="margin-top: 30px;">
            <a href="index.php"><button>Go to Site</button></a>
            <a href="admin.php"><button class="btn-secondary">Go to Admin</button></a>
        </p>

        <?php endif; ?>
    </div>
</body>
</html>
